---
- name: Configure Nginx for React app
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      when: ansible_os_family == 'Debian'  # Adapt for other OS families

    - name: Gather facts about target hosts
      setup:

    - name: Store the public IP of the first host
      set_fact:
        server_public_ip: "{{ ansible_facts.ansible_host }}"

    - name: Create Nginx configuration file
      template:
        src: nginx_react.conf.j2  # template listens to 8080 port
        dest: /etc/nginx/sites-enabled/nginx_react.conf #default config path
        vars:
          server_name: "{{ server_public_ip }}"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Make sure Nginx is running
      systemd:
        state: started
        name: nginx