---
- name: Configure Nginx
  block:
    - name: latest Nginx
      apt:
        name: nginx
        state: latest


#    - name: Gather facts about target hosts
#      setup:
#
#    - name: Store the public IP of the first host
#      set_fact:
#        server_public_ip: "{{ ansible_facts.ansible_host }}"

#    - name: Create Nginx configuration file
#      template:
#        src: myNginx.conf.j2  # template listens to
#        dest: /etc/nginx/sites-enabled/myNginx.conf
#        vars:
#          server_name: "{{ server_public_ip }}"
    - name: Add user to group root
      user:
        name: ubuntu
        groups: root
        state: present

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: transfer Nginx configuration file
      copy:
        src: myNginx.conf
        dest: /etc/nginx/sites-available/myNginx.conf

    - name: Enable website configuration
      file:
        src: /etc/nginx/sites-available/myNginx.conf
        dest: /etc/nginx/sites-enabled/myNginx.conf
        state: link

    - name: restart nginx
      command: sudo systemctl restart nginx

    - name: Make sure Nginx is running
      systemd:
        state: started
        name: nginx


        
        
