---
- name: transfer builds
  hosts: all
  become: true
  remote_user: ubuntu
  vars:
    INSTANCE_IP: "novolty.com"

  tasks:
    - debug:
        var=INSTANCE_IP

  roles:
    - transfer-react
    - transfer-jar
    - nginx-config
    - start-jar

