---

- name: Install dependencies
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
- name: Install pip3 (Debian/Ubuntu)
  ansible.builtin.apt:
    name: python3-pip
    state: present
  when: ansible_os_family == "Debian"
