---
- name: Generate docker-compose.yaml.j2
  template:
    src: docker-compose.yaml.j2
    dest: /home/ubuntu/docker-compose.yaml


- name: Run "docker compose up -d" V2
  docker_compose:
    project_src: /home/ubuntu #server path
    state: present
    restarted: yes

