name: Dispatched Workflow with Secrets and Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6

      - name: Create ansible vault pw file
        run: |
          touch .vault_pass.txt
          chmod 600 .vault_pass.txt
          cat << EOF > .vault_pass.txt
          ${{ secrets.ANSIBLE_VAULT_PW }}
          EOF

      - name: Create scheduler.pem file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > scheduler.pem
          chmod 400 scheduler.pem

      - name: Initialize Terraform
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Apply Terraform changes
        run: terraform apply --auto-approve -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"